 DROP TABLE IF EXISTS Batch;
 DROP TABLE IF EXISTS Warehouse;
 DROP TABLE IF EXISTS Pharmacy;
 DROP TABLE IF EXISTS Product;

 CREATE TABLE Product (
 ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
 Name VARCHAR(255),
 Cost DECIMAL(10,5)
 );

 CREATE TABLE Pharmacy (
 ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
 Name VARCHAR(255),
 Address VARCHAR(255),
 PhoneNumber VARCHAR(30)
 );

 CREATE TABLE Warehouse (
 ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
 Name VARCHAR(255),
 PharmacyId INT NOT NULL,
 CONSTRAINT FK_Warehouse_PharmacyId_Pharmacy_ID FOREIGN KEY(PharmacyId)
 REFERENCES Pharmacy (ID)
 ON DELETE CASCADE
 ON UPDATE CASCADE
 );

 CREATE TABLE Batch (
 ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
 ProductId INT NOT NULL,
 WarehouseId INT NOT NULL,
 ProductCount INT NOT NULL,
 CONSTRAINT FK_Batch_ProductId_Product_ID FOREIGN KEY(ProductId)
 REFERENCES Product (ID)
 ON DELETE CASCADE
 ON UPDATE CASCADE,
 CONSTRAINT FK_Batch_WarehouseId_Warehouse_ID FOREIGN KEY(WarehouseId)
 REFERENCES Warehouse (ID)
 ON DELETE CASCADE
 ON UPDATE CASCADE
 );