
CREATE DATABASE [Pharmacy] 
    ON (NAME = N'Pharmacy', FILENAME = N'D:\Other\SQLServer\MSSQL16.SQLEXPRESS\MSSQL\DATA\Pharmacy.mdf', SIZE = 1024MB, FILEGROWTH = 256MB)
LOG ON (NAME = N'Pharmacy_log', FILENAME = N'D:\Other\SQLServer\MSSQL16.SQLEXPRESS\MSSQL\DATA\Pharmacy_log.ldf', SIZE = 512MB, FILEGROWTH = 125MB)
GO